# Generated by Django 2.1.7 on 2019-04-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190325_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.AutoField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.IntegerField(),
        ),
    ]
