# Generated by Django 2.1.7 on 2019-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190405_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
