# Generated by Django 2.1.7 on 2019-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190409_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='branch',
            field=models.CharField(default='CSE', max_length=4),
        ),
    ]
