# Generated by Django 2.1.7 on 2019-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='branch',
            field=models.CharField(default='CSE', max_length=5),
        ),
    ]
