# Generated by Django 2.1.7 on 2019-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20190412_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificate',
            field=models.BinaryField(),
        ),
    ]
