# Generated by Django 2.1.7 on 2019-04-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20190424_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificate',
            field=models.ImageField(upload_to='leaveApplicaiton/images/'),
        ),
    ]
