# Generated by Django 2.1.7 on 2019-03-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('reg', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('branch', models.CharField(max_length=3, null=True)),
                ('mail', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
