# Generated by Django 2.1.7 on 2019-03-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
