# Generated by Django 2.1.7 on 2019-03-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190303_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='student_acc',
        ),
    ]
