# Generated by Django 2.1.7 on 2019-03-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190303_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='hod_acc',
            fields=[
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=20, null=True)),
                ('hoe_name', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=3)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
