# Generated by Django 2.1.7 on 2019-03-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hod_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hod_acc',
            old_name='hoe_name',
            new_name='hod_name',
        ),
    ]
